version: 2.1

defaults: &defaults
  machine: true
  environment:
    TERM: xterm

jobs:
  build_layer:
    <<: *defaults      
    steps:
    - checkout
    - run:
        name: downloadpb
        command: make downloadpb
    - run:
        name: package
        command: make packagewithpg
    - persist_to_workspace:
        root: ~/
        paths:
          - project

  deploy_layer:
    docker:
    - image: circleci/node:18
    environment:
      TERM: xterm
    steps: 
    - attach_workspace:
        at: ~/  
    - run:
        name: npm i
        command: |
            sudo npm i -g serverless
            npm install
    - run:
        name: deploy
        command: npm run deploy
    - persist_to_workspace:
        root: ~/
        paths:
          - project
              
  create_domain:
    docker:
    - image: circleci/node:18
    environment:
      TERM: xterm
    steps: 
    - attach_workspace:
        at: ~/  
    - run:
        name: npm i
        command: |
            sudo npm i -g serverless
            npm install
    - run:
        name: create_domain
        command: npm run create-domain 
    - persist_to_workspace:
        root: ~/
        paths:
          - project
              

workflows:
  version: 2
  build:
    jobs:
      - build_layer
#       - deploy_layer:
#           requires:
#             - build_layer
#           filters:
#             branches:
#               only: master
