service: ruby-pg-layers
provider:
  name: aws
  profile: ${env:AWS_PROFILE_NAME}
  region: ${env:AWS_REGION}
  
layers:
  pgRuby32:
    path: layer
    description: A Layer to fix postgres support in Ruby 3.2 Lambda functions
    compatibleRuntimes:
      - ruby3.2