service: ruby-pg-layers
provider:
  name: aws
  profile: ${env:AWS_PROFILE_NAME}
  region: ${env:AWS_REGION}
  
layers:
  pgRuby27:
    path: layer
    description: A Layer to fix postgres support in Ruby 2.7 Lambda functions
    compatibleRuntimes:
      - ruby2.7